ins: webConfig
command: |
    (webConfig) => {
        return {
            "all":{
                "/login":"chains/core.login.yaml", 
                "/logout":"chains/core.logout.yaml", 
                "/auth":"chains/core.auth.yaml"
            }
        };
    }
